import type { Video, ReviewItem, MobSlug } from "./types";

// Google's public sample video CDN — stable URLs, no auth.
// These play reliably; the *content* of the clip is mock — the
// caption + validation reasoning is what reads as "Got Milk Mob".
const SAMPLE_VIDEOS = [
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
];

let i = 0;
const nextSrc = () => SAMPLE_VIDEOS[i++ % SAMPLE_VIDEOS.length];

const v = (
  id: string,
  mob: MobSlug,
  user: { handle: string; name: string },
  caption: string,
  durationSec: number,
  thumbnailHint: string,
  uploadedAt: string,
  primarySignals: string[],
  vibeTags: string[],
  confidence = 0.88,
): Video => ({
  id,
  mob,
  caption,
  user,
  durationSec,
  uploadedAt,
  videoUrl: nextSrc(),
  thumbnailHint,
  vibeTags,
  validation: {
    isCampaignRelevant: true,
    confidence,
    primarySignals,
    rejectionReasons: [],
    brandSafetyFlags: [],
    decision: "auto_approve",
  },
});

export const VIDEOS: Video[] = [
  // Kitchen
  v("v-k1", "kitchen",
    { handle: "@miacooks", name: "Mia O." },
    "9 a.m. choreography with my roommate. cereal does not survive.",
    14, "morning kitchen choreography", "2026-05-08T13:42:00Z",
    ["milk visible — gallon jug", "creative activity — choreographed pour", "audience — one"],
    ["pour-over", "morning-light", "cereal-bowl"], 0.91),
  v("v-k2", "kitchen",
    { handle: "@hectorhomes", name: "Hector D." },
    "trying to recreate the 90s commercial in my apartment. mostly succeeded.",
    20, "1990s commercial recreation", "2026-05-08T08:15:00Z",
    ["milk product visible — carton", "tribute / nostalgia framing", "single performer"],
    ["nostalgia", "carton", "homage"], 0.89),
  v("v-k3", "kitchen",
    { handle: "@noahsbreakfast", name: "Noah K." },
    "documenting the great cereal-pour debate of '26.",
    11, "kitchen pour debate", "2026-05-07T22:01:00Z",
    ["milk visible — half-gallon", "creative activity — debate skit"],
    ["debate", "skit", "first-person"], 0.85),

  // Skate
  v("v-s1", "skate",
    { handle: "@calloway", name: "Cal Loway" },
    "kickflip into a sip. one take. send it.",
    8, "skate park sip", "2026-05-08T19:33:00Z",
    ["milk product visible — bottle", "kinetic activity — kickflip", "outdoor location — skate park"],
    ["kickflip", "skate-park", "golden-hour"], 0.93),
  v("v-s2", "skate",
    { handle: "@vert.queen", name: "Reese P." },
    "ramp drop, sip at the top, full send.",
    12, "vert ramp + sip", "2026-05-08T16:11:00Z",
    ["milk visible — small bottle", "physical activity — vert skating", "creative framing"],
    ["vert", "ramp", "full-send"], 0.9),
  v("v-s3", "skate",
    { handle: "@grindkid", name: "Marco T." },
    "5050 grind, milk in the other hand. structural integrity questionable.",
    9, "grinding rail with milk", "2026-05-07T20:42:00Z",
    ["milk carton in hand", "skate trick — 5050"],
    ["grind", "rail", "balance"], 0.86),

  // Beach
  v("v-b1", "beach",
    { handle: "@sandysolomon", name: "Sandy S." },
    "post-swim, salt water and milk, perfect storm.",
    10, "post-swim sip", "2026-05-08T11:28:00Z",
    ["milk product visible — carton", "outdoor location — beach", "post-activity context"],
    ["post-swim", "sand", "salt-air"], 0.88),
  v("v-b2", "beach",
    { handle: "@dunesurf", name: "Lana W." },
    "boardwalk to the bottle. golden hour math.",
    13, "beach golden hour", "2026-05-07T18:45:00Z",
    ["milk product — bottle", "creative camerawork", "sunset lighting"],
    ["sunset", "boardwalk", "slow-pour"], 0.9),
  v("v-b3", "beach",
    { handle: "@reefray", name: "Ray T." },
    "surfboard as a coaster. judge me.",
    7, "surfboard coaster", "2026-05-08T07:12:00Z",
    ["milk visible — half-gallon", "props used creatively"],
    ["surfboard", "props", "salt-spray"], 0.84),

  // Gym
  v("v-g1", "gym",
    { handle: "@jpressbench", name: "JP Bench" },
    "post-set protein shake, but with the OG. respect.",
    11, "post-set sip", "2026-05-08T17:20:00Z",
    ["milk product — carton", "post-workout context", "single performer"],
    ["after-rep", "chalked-hands", "barbell"], 0.86),
  v("v-g2", "gym",
    { handle: "@deltprincess", name: "Delta R." },
    "locker room cheers. milk as the celebration drink.",
    14, "locker room toast", "2026-05-08T12:08:00Z",
    ["milk product — bottle", "group activity — toast", "creative tribute"],
    ["toast", "locker-room", "group-shot"], 0.89),
  v("v-g3", "gym",
    { handle: "@barbellbrian", name: "Brian L." },
    "between sets. fill up. send.",
    9, "between-sets fill", "2026-05-07T15:55:00Z",
    ["milk visible — pint bottle", "gym setting"],
    ["pause", "fill-up", "set-break"], 0.83),

  // Dance
  v("v-d1", "dance",
    { handle: "@flooorpoppy", name: "Poppy K." },
    "studio routine, last beat lands on the sip.",
    16, "studio choreography", "2026-05-08T18:02:00Z",
    ["milk product — bottle", "choreographed routine", "studio setting"],
    ["studio-floor", "in-sync", "neon"], 0.92),
  v("v-d2", "dance",
    { handle: "@livv.dances", name: "Olivia P." },
    "kitchen-to-living-room mini ballet. milk is the prop.",
    13, "ballet mini-routine", "2026-05-08T09:50:00Z",
    ["milk visible — carton as prop", "balletic movement", "single performer"],
    ["ballet", "indoor", "prop-driven"], 0.9),
  v("v-d3", "dance",
    { handle: "@krumpkid", name: "DeMar V." },
    "krumping with a cup. don't try this at home (do).",
    10, "krumping with cup", "2026-05-07T23:18:00Z",
    ["milk in cup", "expressive dance", "creative framing"],
    ["krump", "expressive", "low-light"], 0.85),

  // Pet & Family
  v("v-p1", "pet",
    { handle: "@toddlertom", name: "Tom & Wally" },
    "wally has his own bowl now. it's a whole production.",
    18, "dog bowl production", "2026-05-08T14:17:00Z",
    ["milk visible — bowl", "pet activity", "domestic setting"],
    ["porch-light", "spilled-and-laughing", "kids"], 0.94),
  v("v-p2", "pet",
    { handle: "@familyfreitas", name: "The Freitas" },
    "every kid in the family attempted a mustache. casualties everywhere.",
    21, "family mustache attempt", "2026-05-08T10:30:00Z",
    ["milk visible — half-gallon", "group activity — kids", "comedic framing"],
    ["mustache", "kids", "kitchen-table"], 0.93),
  v("v-p3", "pet",
    { handle: "@thecatbutler", name: "Sofia M." },
    "the cat is unimpressed. as usual.",
    8, "unimpressed cat", "2026-05-07T19:42:00Z",
    ["milk visible — small bowl", "pet present", "comedic framing"],
    ["cat", "deadpan", "domestic"], 0.81),

  // Art
  v("v-a1", "art",
    { handle: "@studiokira", name: "Kira O." },
    "milk as canvas. don't ask about cleanup.",
    15, "milk canvas painting", "2026-05-08T13:00:00Z",
    ["milk product — gallon jug", "creative activity — painting medium", "studio setting"],
    ["studio-window", "process-shot", "messy-table"], 0.88),
  v("v-a2", "art",
    { handle: "@latteart_lou", name: "Lou C." },
    "foam art, then drink. complete the loop.",
    12, "latte foam art", "2026-05-08T08:45:00Z",
    ["milk product — frothed", "creative activity — latte art"],
    ["foam", "barista", "completion"], 0.9),
  v("v-a3", "art",
    { handle: "@stopmotionsam", name: "Sam Y." },
    "claymation milk pour. four hours of frames.",
    19, "claymation pour", "2026-05-07T21:13:00Z",
    ["milk visible — animated still life", "creative activity — stop motion"],
    ["claymation", "stop-motion", "studio"], 0.87),

  // Outdoors
  v("v-o1", "outdoors",
    { handle: "@trailtrina", name: "Trina A." },
    "summit toast at 11k feet. don't drop the carton.",
    14, "summit toast", "2026-05-08T20:11:00Z",
    ["milk product — carton", "outdoor — summit", "creative tribute"],
    ["alpine", "summit", "tail-wind"], 0.92),
  v("v-o2", "outdoors",
    { handle: "@thermosbros", name: "The Bros" },
    "morning rain, thermos full. who needs coffee.",
    11, "rainy morning thermos", "2026-05-08T07:55:00Z",
    ["milk product — thermos pour", "outdoor location"],
    ["rain", "thermos", "trail"], 0.86),
  v("v-o3", "outdoors",
    { handle: "@campfirecase", name: "Case M." },
    "campfire pour, cast iron, bedtime.",
    9, "campfire pour", "2026-05-07T23:49:00Z",
    ["milk product — visible at campfire"],
    ["campfire", "cast-iron", "twilight"], 0.84),
];

export function videosByMob(slug: MobSlug) {
  return VIDEOS.filter((v) => v.mob === slug);
}

export function videoById(id: string) {
  return VIDEOS.find((v) => v.id === id);
}

export const REVIEW_QUEUE: ReviewItem[] = [
  {
    ...v("v-r1", "kitchen",
      { handle: "@jakebackyard", name: "Jake T." },
      "love this milk. been drinking it since college.",
      22, "talking about milk", "2026-05-09T08:32:00Z",
      ["milk product visible — carton"],
      [], 0.54),
    validation: {
      isCampaignRelevant: false,
      confidence: 0.54,
      primarySignals: ["milk product visible — carton"],
      rejectionReasons: ["no creative activity present", "static framing"],
      brandSafetyFlags: [],
      decision: "review",
    },
    reasonForReview: "Confidence below auto-approve threshold (0.75); no creative-activity signal but no brand-safety flags either.",
  },
  {
    ...v("v-r2", "art",
      { handle: "@gallerymax", name: "Max V." },
      "abstract piece — milk and ink mixing in real time.",
      16, "abstract milk + ink", "2026-05-09T10:15:00Z",
      ["milk product — partial frame"],
      [], 0.62),
    validation: {
      isCampaignRelevant: true,
      confidence: 0.62,
      primarySignals: ["milk visible — bowl", "creative activity — fluid art"],
      rejectionReasons: [],
      brandSafetyFlags: ["unfamiliar substance — likely ink, model unsure"],
      decision: "review",
    },
    reasonForReview: "Brand-safety flag raised — substance in frame may be ink. Operator should confirm.",
  },
  {
    ...v("v-r3", "dance",
      { handle: "@dancerdyl", name: "Dylan H." },
      "improv routine. milk shows up at the end.",
      19, "improv with late prop", "2026-05-09T11:42:00Z",
      ["creative activity — choreography"],
      [], 0.68),
    validation: {
      isCampaignRelevant: true,
      confidence: 0.68,
      primarySignals: ["creative activity — choreography", "milk appears at 00:14"],
      rejectionReasons: [],
      brandSafetyFlags: [],
      decision: "review",
    },
    reasonForReview: "Milk appears late in the clip. Operator should confirm intent matches campaign brief.",
  },
];
